# Generated by Django 5.1.2 on 2024-10-17 01:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name_variation', models.CharField(blank=True, max_length=255, null=True)),
                ('docket_id', models.CharField(max_length=255)),
                ('case_number', models.CharField(blank=True, max_length=255, null=True)),
                ('case_type', models.CharField(blank=True, max_length=255, null=True)),
                ('court', models.CharField(blank=True, max_length=255, null=True)),
                ('caption', models.CharField(blank=True, max_length=2000, null=True)),
                ('url', models.URLField(blank=True, null=True, verbose_name='URL')),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('filed_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('found_date', models.DateTimeField(blank=True, null=True)),
                ('is_scraped', models.BooleanField(default=False)),
                ('scraped_date', models.DateTimeField(blank=True, null=True)),
                ('gbruno_score', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('case_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'ordering': [models.OrderBy(models.F('case_date'), descending=True, nulls_last=True)],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CaseDetailsCT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(blank=True, max_length=1000, null=True)),
                ('pty_no', models.CharField(blank=True, max_length=255, null=True)),
                ('self_rep', models.BooleanField(default=False)),
                ('prefix', models.CharField(blank=True, max_length=255, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('last_action_date', models.DateField(blank=True, null=True)),
                ('list_type', models.CharField(blank=True, max_length=255, null=True)),
                ('list_claim_date', models.DateField(blank=True, null=True)),
                ('judge', models.CharField(blank=True, max_length=255, null=True)),
                ('disposition', models.CharField(blank=True, max_length=255, null=True)),
                ('disposition_date', models.DateField(blank=True, null=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ct_details', to='web.case')),
            ],
        ),
        migrations.CreateModel(
            name='CaseDetailsMN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mn_details', to='web.case')),
            ],
        ),
        migrations.CreateModel(
            name='CaseDetailsNY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('efiling_status', models.CharField(blank=True, max_length=255, null=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ny_details', to='web.case')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='web.company'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('unique_id', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=255, verbose_name='URL')),
                ('is_downloaded', models.BooleanField(default=False)),
                ('download_date', models.DateTimeField(blank=True, null=True)),
                ('relative_path', models.CharField(blank=True, max_length=255, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='web.case')),
            ],
            options={
                'unique_together': {('case', 'unique_id')},
            },
        ),
        migrations.CreateModel(
            name='DocumentDetailsCT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_no', models.CharField(blank=True, max_length=255, null=True)),
                ('filed_date', models.DateField(blank=True, null=True)),
                ('filed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('arguable', models.CharField(blank=True, max_length=255, null=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ct_details', to='web.document')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentDetailsMN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mn_details', to='web.document')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentDetailsNY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, max_length=255, null=True)),
                ('filed_by', models.TextField(blank=True, max_length=255, null=True)),
                ('filed_date', models.DateField(blank=True, null=True)),
                ('received_date', models.DateField(blank=True, null=True)),
                ('status_document_url', models.URLField(blank=True, max_length=255, null=True)),
                ('status_document_name', models.CharField(blank=True, max_length=255, null=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ny_details', to='web.document')),
            ],
        ),
        migrations.AddField(
            model_name='case',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='web.state'),
        ),
        migrations.CreateModel(
            name='CompanyNameVariation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_variations', to='web.company')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('company', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='case',
            unique_together={('state', 'docket_id')},
        ),
    ]
