# Generated by Django 5.0.2 on 2024-02-22 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_alter_company_options_company_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInputName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.AlterField(
            model_name='case',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='web.companyinputname'),
        ),
        migrations.DeleteModel(
            name='Company',
        ),
    ]
