# Generated by Django 5.0.2 on 2024-02-22 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_companyinputname_alter_case_company_delete_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='caption',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='file_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='received_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='return_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='url',
            field=models.URLField(),
        ),
    ]
