# Generated by Django 5.0.2 on 2024-02-22 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_alter_case_caption_alter_case_case_number_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companyinputname',
            options={'verbose_name_plural': 'Company Inputs'},
        ),
    ]
