# Generated by Django 5.0.2 on 2024-02-22 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_alter_companyinputname_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinputname',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
