# Generated by Django 5.0.2 on 2024-03-07 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_alter_companyinputname_name'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CompanyInputName',
            new_name='Company',
        ),
        migrations.DeleteModel(
            name='Case',
        ),
    ]
