# Generated by Django 5.0.2 on 2024-03-07 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_case'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDetailsCT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_name', models.CharField(blank=True, max_length=255, null=True)),
                ('party_name', models.CharField(blank=True, max_length=255, null=True)),
                ('pty_no', models.CharField(blank=True, max_length=255, null=True)),
                ('self_rep', models.BooleanField(default=False)),
                ('prefix', models.CharField(blank=True, max_length=255, null=True)),
                ('file_date', models.DateField(blank=True, null=True)),
                ('return_date', models.DateField(blank=True, null=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ct_details', to='web.case')),
            ],
        ),
        migrations.CreateModel(
            name='CaseDetailsNY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_date', models.DateField(blank=True, null=True)),
                ('efiling_status', models.CharField(blank=True, max_length=255, null=True)),
                ('case_status', models.CharField(blank=True, max_length=255, null=True)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('court', models.CharField(blank=True, max_length=255, null=True)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ny_details', to='web.case')),
            ],
        ),
    ]
