# Generated by Django 5.0.2 on 2024-03-07 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0010_alter_company_options_companynamevariation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='companynamevariation',
            unique_together={('company', 'name')},
        ),
    ]
