# Generated by Django 5.0.2 on 2024-03-07 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0012_case_company_name_case_state_alter_case_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casedetailsny',
            name='court',
        ),
    ]
