# Generated by Django 5.0.2 on 2024-03-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0013_remove_casedetailsny_court'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casedetailsny',
            name='caption',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
