# Generated by Django 5.0.2 on 2024-03-07 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0014_alter_casedetailsny_caption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casedetailsct',
            name='case_name',
        ),
        migrations.RemoveField(
            model_name='casedetailsny',
            name='caption',
        ),
        migrations.AddField(
            model_name='case',
            name='caption',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='gbruno_score',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
