# Generated by Django 5.0.2 on 2024-03-07 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_remove_casedetailsct_case_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('document_id', models.CharField(blank=True, max_length=255, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='web.case')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='web.company')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentDetailsCT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_no', models.CharField(blank=True, max_length=255, null=True)),
                ('file_date', models.DateField(blank=True, null=True)),
                ('filed_by', models.CharField(blank=True, max_length=255, null=True)),
                ('arguable', models.CharField(blank=True, max_length=255, null=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ct_details', to='web.document')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentDetailsNY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_document_url', models.URLField(blank=True, max_length=255, null=True)),
                ('status_document_name', models.CharField(blank=True, max_length=255, null=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ny_details', to='web.document')),
            ],
        ),
    ]
