# Generated by Django 5.0.2 on 2024-03-09 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_rename_company_name_case_company_name_variation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='company',
        ),
    ]
