# Generated by Django 5.0.2 on 2024-03-10 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_case_is_scraped_case_scraped_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='case_id',
            new_name='docket_id',
        ),
        migrations.AlterUniqueTogether(
            name='case',
            unique_together={('state', 'docket_id')},
        ),
    ]
