# Generated by Django 5.0.2 on 2024-03-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0020_rename_case_id_case_docket_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='filed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='received_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
