# Generated by Django 5.0.2 on 2024-03-12 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0021_case_filed_date_case_received_date_case_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documentdetailsct',
            old_name='file_date',
            new_name='filed_date',
        ),
    ]
