# Generated by Django 5.0.3 on 2024-03-13 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0022_rename_file_date_documentdetailsct_filed_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='download_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
