# Generated by Django 5.0.3 on 2024-03-13 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0023_alter_document_download_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='casedetailsct',
            name='file_date',
        ),
        migrations.RemoveField(
            model_name='casedetailsny',
            name='case_status',
        ),
        migrations.RemoveField(
            model_name='casedetailsny',
            name='received_date',
        ),
    ]
