# Generated by Django 5.0.3 on 2024-03-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0025_remove_documentdetailsny_status_document_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='found_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
