# Generated by Django 5.0.3 on 2024-03-17 23:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0027_alter_document_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseDetailsMN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mn_details', to='web.case')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentDetailsMN',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='mn_details', to='web.document')),
            ],
        ),
    ]
