# Generated by Django 5.0.3 on 2024-03-20 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0028_casedetailsmn_documentdetailsmn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companynamevariation',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
