# Generated by Django 5.0.3 on 2024-03-20 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0029_alter_companynamevariation_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='companynamevariation',
            options={'ordering': ['name']},
        ),
    ]
