# Generated by Django 5.0.3 on 2024-03-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0030_alter_companynamevariation_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='case_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
