# Generated by Django 5.0.3 on 2024-03-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0031_case_case_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_date',
            field=models.DateField(default=None),
            preserve_default=False,
        ),
    ]
