# Generated by Django 5.0.3 on 2024-03-28 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0033_remove_casedetailsny_status_document_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='case_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
