# Generated by Django 5.0.3 on 2024-04-03 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0034_alter_case_case_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentdetailsny',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='documentdetailsny',
            name='filed_by',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='documentdetailsny',
            name='filed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentdetailsny',
            name='received_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
