# Generated by Django 5.0.3 on 2024-04-04 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0035_documentdetailsny_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name_plural': 'Companies'},
        ),
    ]
