# Generated by Django 5.0.3 on 2024-04-04 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0036_alter_company_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='case',
            options={'ordering': [models.OrderBy(models.F('case_date'), descending=True, nulls_last=True)]},
        ),
    ]
