# Generated by Django 5.0.3 on 2024-04-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0037_alter_case_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casedetailsct',
            name='party_name',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
