# Generated by Django 5.0.3 on 2024-04-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0038_alter_casedetailsct_party_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='casedetailsct',
            name='disposition',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='casedetailsct',
            name='disposition_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casedetailsct',
            name='judge',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='casedetailsct',
            name='last_action_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casedetailsct',
            name='list_claim_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='casedetailsct',
            name='list_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
