# Generated by Django 5.0.3 on 2024-04-07 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0039_casedetailsct_disposition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='document',
            name='url',
            field=models.URLField(default=None, max_length=255, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
