# Generated by Django 5.0.3 on 2024-04-07 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0041_alter_document_document_id_alter_document_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='document_id',
            new_name='unique_id',
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('case', 'unique_id')},
        ),
    ]
