# Generated by Django 5.0.3 on 2024-04-07 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0042_rename_document_id_document_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='docket_id',
            field=models.CharField(max_length=255),
        ),
    ]
