name: Deploy to EC2 on Master Merge

on:
  push:
    branches:
      - KYRT_NY_Cases

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          command_timeout: 120m
          script: |
            cd /home/ubuntu/KYRT
            git fetch --all                     # Fetch the latest state of the remote
            git reset --hard origin/master      # Reset the local branch to match the fetched state of the remote master
            git clean -fd                       # Remove untracked files and directories
            docker compose up --build --detach